security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            remember_me:
                secret: "%secret%"
                lifetime: 31536000
                path: /
                domain:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path: /login
                check_path: /login_check
            logout:       true
            anonymous:    true
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           /connect/check-facebook
                    google:             /connect/check-google

                login_path:        /connect
                use_forward:       false
                failure_path:      /connect

                oauth_user_provider:
                    service: my.custom.user_provider


    access_control:
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }