# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    imgs_directory: '%kernel.root_dir%/../web/uploads/brochures'
#    parameter_name: value

services:
    my.custom.user_provider:
        class:        AppBundle\Security\Core\User\MyFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { facebook: facebook_id }]